### ISSUE TITLE
Adding theme

### ISSUE THREAD

**Issue by charly3pins** [isgj/gin-web#1]
What do you think if we add a created theme instead of creating new from scratch and then we adapt it with our needs?

I see these two [Kraiklyn](https://themes.gohugo.io/kraiklyn/) and [docuapi](https://themes.gohugo.io/docuapi/ )that could be useful

I've been working with Hugo some months ago so I can help you in the design and fucntionalities you need

**Comment by charly3pins** [comment]
Okay @isgj I'm okay too. So if you agree, we can create a task list here or in separate issues to have the next steps clear and don't do same work twice. What do you think?

**Comment by isgj** [comment]
yeah sure

**Comment by isgj** [comment]
Added a little section in the README
